name: rec-building-twrp

on:
  watch:
    types: [started]
  workflow_dispatch:
   inputs:
     twrp_branch:
       description: 'twrp_branch'
       required: true
       default: 'twrp-9.0'
     device_code:
       description: 'device_code'
       required: true
       default: 'tiffany'
     dt_remote:
       description: 'dt_remote(github or gitlab)'
       required: true
       default: 'github'
     dt_url:
       description: 'dt_url'
       required: true
       default: 'laityts/android_device_xiaomi_tiffany-twrp'
     dt_branch:
       description: 'dt_branch'
       required: true
       default: 'android-9.0'
     dt_path:
       description: 'dt_path'
       required: true
       default: 'device/xiaomi/tiffany'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
              
    - name: Initial
      run: |
        sudo apt-get update -y
        sudo apt-get install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip jq python2
      
    - name: Get variables
      run: |
        if [[ -z "${{ github.event.inputs.twrp_branch }}" ]]; then
            echo "::set-output name=twrp_branch::$(jq -r '.twrp_branch' config.json)"
        else
            echo "::set-output name=twrp_branch::${{ github.event.inputs.twrp_branch }}"
        fi
        if [[ -z "${{ github.event.inputs.dt_url }}" ]]; then
            echo "::set-output name=dt_url::$(jq -r '.dt_url' config.json)"
        else
            echo "::set-output name=dt_url::${{ github.event.inputs.dt_url }}"
        fi
        if [[ -z "${{ github.event.inputs.dt_remote }}" ]]; then
            echo "::set-output name=dt_remote::$(jq -r '.dt_remote' config.json)"
        else
            echo "::set-output name=dt_remote::${{ github.event.inputs.dt_remote }}"
        fi
        if [[ -z "${{ github.event.inputs.dt_branch }}" ]]; then
            echo "::set-output name=dt_branch::$(jq -r '.dt_branch' config.json)"
        else
            echo "::set-output name=dt_branch::${{ github.event.inputs.dt_branch }}"
        fi
        if [[ -z "${{ github.event.inputs.dt_path }}" ]]; then
            echo "::set-output name=dt_path::$(jq -r '.dt_path' config.json)"
        else
            echo "::set-output name=dt_path::${{ github.event.inputs.dt_path }}"
        fi
        if [[ -z "${{ github.event.inputs.device_code }}" ]]; then
            echo "::set-output name=device_code::$(jq -r '.device_code' config.json)"
        else
            echo "::set-output name=device_code::${{ github.event.inputs.device_code }}"
        fi
        echo "::set-output name=twrp_url::$(jq -r '.twrp_url' config-twrp.json)"
        echo "::set-output name=git_username::$(jq -r '.git_username' config-twrp.json)"
        echo "::set-output name=git_email::$(jq -r '.git_email' config-twrp.json)"
        echo "::set-output name=use_own_dt::$(jq -r '.use_own_dt' config-twrp.json)"
        echo "::set-output name=date::$(date +%F)"
        echo "::set-output name=day::$(date +%Y%m%d)"
      id: var
      
    - name: Install Repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        
    - name: Initialize Repair Manifest
      run: git clone https://github.com/TeamWin/buildtree_manifests.git repair/
      
    - name: Initialize a Repo client
      run: |
        ls /usr/bin/python*
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 2
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1
        PATH=~/bin:$PATH
        mkdir workspace
        cd workspace
        echo "::set-output name=pwd::$(pwd)"
        git config --global user.name "${{ steps.var.outputs.git_username }}"
        git config --global user.email "${{ steps.var.outputs.git_email }}"
        repo init --depth=1 -u ${{ steps.var.outputs.twrp_url }} -b ${{ steps.var.outputs.twrp_branch }}
        mkdir .repo/local_manifests
      id: pwd

    - name: Clone your own device tree
      if: steps.var.outputs.use_own_dt == 'true'
      run: |
        sed -i 's!dt_url!${{ steps.var.outputs.dt_url }}!g' device.xml
        sed -i 's!dt_path!${{ steps.var.outputs.dt_path }}!g' device.xml
        sed -i 's!dt_remote!${{ steps.var.outputs.dt_remote }}!g' device.xml
        sed -i 's!dt_branch!${{ steps.var.outputs.dt_branch }}!g' device.xml
        cp device.xml workspace/.repo/local_manifests/ 
          
    - name: Repo sync
      run: |
        PATH=~/bin:$PATH
        cd workspace
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
        ls -al

    - id: build
      name: Start Building
      run: |
        PATH=~/bin:$PATH
        cd ${{ steps.pwd.outputs.pwd }}
        tree device
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch omni_${{ steps.var.outputs.device_code }}-eng 
        mka recoveryimage -j$(nproc --all)
        ls -al
        TWRP_VERSION=$(cat bootable/recovery/variables.h | grep TW_MAIN_VERSION_STR | cut -d\" -s -f2)
        echo "TWRP_VERSION: $TWRP_VERSION"
        mv out/target/product/${{ steps.var.outputs.device_code }}/recovery.img out/target/product/${{ steps.var.outputs.device_code }}/TWRP-${TWRP_VERSION}_${{ steps.var.outputs.device_code }}-${{ steps.var.outputs.day }}.img
        echo "::set-output name=TWRP_VERSION::${TWRP_VERSION}"
        
    - name: Upload REC
      uses: softprops/action-gh-release@v1
      with:
        files: workspace/out/target/product/${{ steps.var.outputs.device_code }}/TWRP-${{ steps.build.outputs.TWRP_VERSION }}_${{ steps.var.outputs.device_code }}-${{ steps.var.outputs.day }}.img
        name: TWRP ${{ steps.build.outputs.TWRP_VERSION }} ${{ steps.var.outputs.device_code }} ${{ steps.var.outputs.day }}
        tag_name: ${{ github.run_id }}
        body: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ secrets.TWRP }}
